### ISSUE TITLE
unable to change folder icon

### ISSUE THREAD

**Issue by ChinmayaGit** [demberto/FolderIkon#1]
first i pip install folderikon

then,
python folderikon

`python folderikon
python: can't open file 'C:\\Users\\xyz\\OneDrive\\Desktop\\New folder\\folderikon': [Errno 2] No such file or directory`

not worked then,
folderikon

`folderikon
'folderikon' is not recognized as an internal or external command,
operable program or batch file.`

not worked

i create a new folder inside that folder ico is present

**Comment by demberto** [comment]
the first command you tried is incorrect. its
```ps1
python -m folderikon
```

and the second won't work unless Python's `Scripts` folder is in `PATH`. you should have noticed a warning about the same when you installed folderikon.

**Comment by ChinmayaGit** [comment]
> the first command you tried is incorrect. its
> 
> ```powershell
> python -m folderikon
> ```
> 
> and the second won't work unless Python's `Scripts` folder is in `PATH`. you should have noticed a warning about the same when you installed folderikon.

thanks it worked great.
